const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const path=require('path');
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1024,height:940},reducedMotion:'reduce'});
 const errors=[];page.on('pageerror',e=>errors.push(String(e)));
 await page.goto('file://'+path.resolve('lumina-walk-v1/lumina-walk-player.html'));
 await page.waitForFunction(()=>document.querySelector('#frames button[aria-pressed="true"]'));
 const initial=await page.locator('#front').evaluate(c=>c.toDataURL());
 await page.click('#step');
 const stepped=await page.locator('#front').evaluate(c=>c.toDataURL());
 if(initial===stepped)throw Error('Step did not change canvas');
 await page.click('#parts');
 const parts=await page.locator('#front').evaluate(c=>c.toDataURL());
 if(parts===stepped)throw Error('Parts toggle did not change canvas');
 await page.screenshot({path:'player-parts-check.png',fullPage:true});
 await page.click('#parts');
 await page.click('#play');
 const a=await page.locator('#phase').textContent();
 await page.waitForTimeout(390);
 const b=await page.locator('#phase').textContent();
 if(a===b)throw Error('Animation did not advance');
 await page.click('#play');
 await page.screenshot({path:'player-desktop-check.png',fullPage:true});
 await page.setViewportSize({width:375,height:812});
 await page.screenshot({path:'player-mobile-check.png',fullPage:true});
 const over=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 if(over)throw Error('Mobile horizontal overflow');
 if(errors.length)throw Error(errors.join('\n'));
 console.log(JSON.stringify({step:true,parts:true,animation:true,mobileOverflow:false,pageErrors:errors}));
 await browser.close();
})();
