// Builds light web copies of the delivered art in game/assets/requested/final/.
// The deliveries are kept untouched (1024px PNGs, ~12MB in total); this writes
// final/_web/<kind>/<name>.webp, trimmed to the drawing and scaled to what the game needs, plus
// final/_web/manifest.json. pack-png-v019.js loads the _web copy when the manifest lists it and
// falls back to the original PNG otherwise. Floors are left alone (small, used as a texture).
// Usage: npx http-server -p 8765 -s -c-1 .   (repo root, in another shell)
//        node tools/build_final_web.js
const {chromium}=require(process.env.PW||'playwright');
const fs=require('fs'),path=require('path');
const FINAL=path.join(__dirname,'..','game','assets','requested','final'),OUT=path.join(FINAL,'_web');
// longest side in px after trimming; icons are also centred on a square with even padding
const MAX={monsters:320,props:384,nutera:160,icons:96};
const SPECIAL={'nutera/sigil':384,'nutera/estella_logo':720};
(async()=>{
 const index=JSON.parse(fs.readFileSync(path.join(FINAL,'index.json'),'utf8'));
 const files=[];
 for(const kind of Object.keys(MAX))for(const e of index[kind]||[]){const name=String(e).replace(/^.*\//,'').replace(/\.png$/,'');if(fs.existsSync(path.join(FINAL,kind,name+'.png')))files.push({kind,name,max:SPECIAL[kind+'/'+name]||MAX[kind],square:kind==='icons'})}
 const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'}).catch(()=>chromium.launch());
 const p=await b.newPage();
 await p.goto('http://localhost:8765/game/battle.css');
 const res=await p.evaluate(async files=>{
  const L=s=>new Promise((r,j)=>{const i=new Image();i.onload=()=>r(i);i.onerror=()=>j(new Error(s));i.src=s});
  const out={};
  for(const f of files){
   const im=await L(`/game/assets/requested/final/${f.kind}/${f.name}.png`);
   const c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;const g=c.getContext('2d');g.drawImage(im,0,0);
   const d=g.getImageData(0,0,c.width,c.height).data;let x0=c.width,y0=c.height,x1=-1,y1=-1;
   for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++)if(d[(y*c.width+x)*4+3]>8){if(x<x0)x0=x;if(x>x1)x1=x;if(y<y0)y0=y;if(y>y1)y1=y}
   if(x1<0){x0=0;y0=0;x1=c.width-1;y1=c.height-1}
   let w=x1-x0+1,h=y1-y0+1,src=document.createElement('canvas');src.width=w;src.height=h;src.getContext('2d').drawImage(c,x0,y0,w,h,0,0,w,h);
   // step down by halves for a clean downscale
   const k=Math.min(1,(f.square?f.max*.84:f.max-4)/Math.max(w,h));const tw=Math.max(1,Math.round(w*k)),th=Math.max(1,Math.round(h*k));
   while(src.width/2>=tw&&src.height/2>=th){const n=document.createElement('canvas');n.width=Math.round(src.width/2);n.height=Math.round(src.height/2);const ng=n.getContext('2d');ng.imageSmoothingQuality='high';ng.drawImage(src,0,0,n.width,n.height);src=n}
   const o=document.createElement('canvas');
   if(f.square){o.width=o.height=f.max}else{o.width=tw+4;o.height=th+4}
   const og=o.getContext('2d');og.imageSmoothingQuality='high';og.drawImage(src,(o.width-tw)/2,(o.height-th)/2,tw,th);
   out[f.kind+'/'+f.name]={url:o.toDataURL('image/webp',.9),w:o.width,h:o.height,src:[im.naturalWidth,im.naturalHeight]};
  }
  return out;
 },files);
 const manifest={note:'generated by tools/build_final_web.js; do not edit',files:{}};
 let before=0,after=0;
 for(const [k,v] of Object.entries(res)){
  if(!v.url.startsWith('data:image/webp'))throw new Error('this browser cannot encode WebP');
  const f=path.join(OUT,k+'.webp');fs.mkdirSync(path.dirname(f),{recursive:true});const buf=Buffer.from(v.url.split(',')[1],'base64');fs.writeFileSync(f,buf);
  before+=fs.statSync(path.join(FINAL,k+'.png')).size;after+=buf.length;
  manifest.files[k]={file:k+'.webp',size:[v.w,v.h],source:v.src};
 }
 fs.writeFileSync(path.join(OUT,'manifest.json'),JSON.stringify(manifest,null,1)+'\n');
 console.log(`wrote ${Object.keys(res).length} files: ${(before/1048576).toFixed(1)}MB -> ${(after/1048576).toFixed(2)}MB`);
 await b.close();
})();
